#include <iostream>
using namespace std;
/* DONE AND DUSTED BY LINUS */

int main(int argc, char** argv) {
	float a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z;
	float A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z;
	float A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1;
	float A2,B2,C2,D2,E2,F2,G2,H2,I2,J2,K2,L2,M2,N2,O2,P2,Q2,R2,S2;
	float A3,B3,C3,D3,E3,F3,G3,H3,I3,J3,K3,L3,M3,N3,O3,P3,Q3,R3,S3;
	float A4,B4,C4,D4,E4,F4,G4,H4,I4,J4,K4,L4,M4,N4,O4,P4,Q4,R4;
	float A5,B5,C5,D5,E5,F5,G5,H5,I5,J5,K5,L5,M5,N5,O5,P5,Q5,R5;
	float A6,B6,C6,D6,E6,F6,G6,H6,I6,J6,K6,L6,M6,N6,O6,P6,Q6,R6;
	float A7,B7,C7,D7,E7,F7,G7,H7,I7,J7,K7,L7,M7,N7,O7,P7,Q7,R7;
	float A8,B8,C8,D8,E8,F8,G8,H8,I8,J8,K8,L8,M8,N8,O8,P8,Q8,R8;
	float A9,B9,C9,D9,E9,F9,G9,H9,I9,J9,K9,L9,M9,N9,O9,P9,Q9,R9;
	const double PI=3.142;
	cout<<" ---------- For 10 rpm V-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>a;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>b>>c>>d>>e>>f;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>g;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>h>>i>>j>>k>>l;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>m;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>n>>o>>p>>q>>r>>s;
	cout<<" ---------- For 10 rpm Flat-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>t;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>u>>v>>w>>x>>y;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>z;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>A>>B>>C>>D>>E;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>F;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>G>>H>>I>>J>>K;
	
	
	cout<<" ---------- For 15 rpm V-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>L;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>M>>N>>O>>P>>Q;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>R;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>S>>T>>U>>V>>W;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>X;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>Y>>Z>>A1>>A2>>A3;
	cout<<" ---------- For 15 rpm Flat-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>A4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>A5>>A6>>A7>>A8>>A9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>B1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>B2>>B3>>B4>>B5>>B6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>B7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>B8>>B9>>C1>>C2>>C3;
	
	
	cout<<" ---------- For 5 rpm V-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>C4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>C5>>C6>>C7>>C8>>C9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>D1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>D2>>D3>>D4>>D5>>D6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>D7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>D8>>D9>>E1>>E2>>E3;
	cout<<" ---------- For 5 rpm Flat-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>E4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>E5>>E6>>E7>>E8>>E9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>F1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>F2>>F3>>F4>>F5>>F6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>F7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>F8>>F9>>G1>>G2>>G3;
	
	
	cout<<" ---------- For Considering the centrifugal effects ----------"<<"\n";
	cout<<" ---------- For 10 rpm V-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>G4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>G5>>G6>>G7>>G8>>G9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>H1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>H2>>H3>>H4>>H5>>H6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>H7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>H8>>H9>>I1>>I2>>I3;
	cout<<" ---------- For 10 rpm Flat-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>I4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>I5>>I6>>I7>>I8>>I9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>J1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>J2>>J3>>J4>>J5>>J6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>J7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>J8>>J9>>K1>>K2>>K3;
	
	
	cout<<" ---------- For 15 rpm V-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>K4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>K5>>K6>>K7>>K8>>K9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>L1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>L2>>L3>>L4>>L5>>L6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>L7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>L8>>L9>>M1>>M2>>M3;
	cout<<" ---------- For 15 rpm Flat-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>M4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>M5>>M6>>M7>>M8>>M9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>N1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>N2>>N3>>N4>>N5>>N6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>N7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>N8>>N9>>O1>>O2>>O3;
	
	
	cout<<" ---------- For 5 rpm V-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>O4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>O5>>O6>>O7>>O8>>O9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>P1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>P2>>P3>>P4>>P5>>P6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>P7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>P8>>P9>>Q1>>Q2>>Q3;
	cout<<" ---------- For 5 rpm Flat-Belt ----------"<<"\n";
	cout<<"Enter your values of first T2 "<<"\n";
	cin>>Q4;
	cout<<"Enter your values of first T1 "<<"\n";
	cin>>Q5>>Q6>>Q7>>Q8>>Q9;
	cout<<"Enter your values of second T2 "<<"\n";
	cin>>R1;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>R2>>R3>>R4>>R5>>R6;
	cout<<"Enter your values of third T2 "<<"\n";
	cin>>R7;
	cout<<"Enter your values of second T1 "<<"\n";
	cin>>R8>>R9>>S1>>S2>>S3;
	return 0;
}
